version: "3.8"

services:
  db:
    container_name: mysqldb
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    expose:
      - 3307
    networks:
     symfony-net:
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
    networks:
     symfony-net:


  maildev:
    image: maildev/maildev
    container_name: maildev_container
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      symfony-net:
  
  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      symfony-net:




networks:
    symfony-net:
volumes:
    db-data: