version: "3.8"

services:
  db:
    container_name: mysqldb
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    expose:
      - 3307


volumes:
    db-data: